apiVersion: apps/v1
kind: Deployment
metadata:
 name: mischievous-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: my-app
 template:
   metadata:
     labels:
       app: my-app
   spec:
     containers:
     - name: my-container
       image: nginx:latest
       resources:
         limits:
           memory: "300Mi"  
           cpu: "600m"       
         requests:
           memory: "125Mi"  
           cpu: "100m"      

